services:
  xmrig:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: monero_xmrig_miner
    restart: unless-stopped
    
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - WORKER_NAME=${WORKER_NAME:-miner_docker}
      - POOL_URL=${POOL_URL:-gulf.moneroocean.stream}
      - DONATE_LEVEL=${DONATE_LEVEL:-0}
      - MAX_THREADS_PERCENT=${MAX_THREADS_PERCENT:-25}
      - PAUSE_ON_BATTERY=${PAUSE_ON_BATTERY:-false}
      - PAUSE_ON_ACTIVE=${PAUSE_ON_ACTIVE:-false}
      - FORCE_THREAD_COUNT=${FORCE_THREAD_COUNT:-2}
    
    # CPU configuration (Docker level - for container isolation)
    deploy:
      resources:
        limits:
          cpus: '${CPU_COUNT:-2.0}'
          memory: ${MEMORY_LIMIT:-1g}
        reservations:
          cpus: '0.5'
          memory: 256m
    
    # Mount logs for persistence
    volumes:
      - ./logs:/app/logs
      - ./docker-configs:/app/configs
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    # Health check override
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s