services:
  xmrig:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "xmrig-${RANDOM_SUFFIX:-$(shell head /dev/urandom | tr -dc a-z0-9 | head -c 8)}"
    restart: unless-stopped
    
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - WORKER_NAME=${WORKER_NAME:-miner_docker_$(shell head /dev/urandom | tr -dc a-z0-9 | head -c 6)}
      - POOL_URL=${POOL_URL:-gulf.moneroocean.stream}
      - DONATE_LEVEL=${DONATE_LEVEL:-0}
      - MAX_THREADS_PERCENT=${MAX_THREADS_PERCENT:-75}
      - PAUSE_ON_BATTERY=${PAUSE_ON_BATTERY:-false}
      - PAUSE_ON_ACTIVE=${PAUSE_ON_ACTIVE:-false}
    
    # CPU configuration
    cpus: ${CPU_COUNT:-2}
    cpu_percent: ${CPU_PERCENT:-75}
    mem_limit: ${MEMORY_LIMIT:-1g}
    
    # Mount logs for persistence
    volumes:
      - ./docker/logs:/app/logs
      - ./docker/docker-configs:/app/configs
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    # Health check override
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Optional: Use secrets for wallet address (more secure)
# Uncomment the sections below to use Docker secrets instead of environment variables

# secrets:
#   wallet_address:
#     file: ./secrets/wallet_address.txt

# Then in the service definition, replace the WALLET_ADDRESS environment variable with:
# secrets:
#   - wallet_address
# And modify entrypoint.sh to read from /run/secrets/wallet_address